# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

# Basic
name:               "anifilm's Portfolio Blog"



author:
  name:             anifilm
  facebook:         your-id
  github:           anifilm
  linkedin:         your-id
  email:            anifilm02@gmail.com

 ##   youtubeUser:      your-id
##   youtubeChannel:   your-id
##   twitter:          your-id
##   stackoverflow:    your-id
##   quora:            your-id
##   pinterest:        your-id
##   googlePlus:       your-id
##   instagram:        your-id
##   reddit:           your-id
##   medium:           your-id
##   tumblr:           your-id
  
# Google-analytics
google-analytics:
  id:               ""

# Disqus
disqus:
  id:               "anifilm-blog"

# URL
url:                "https://anifilm.github.io" # the base hostname & protocol for your site
#url:                "http://localhost:4000" # use this url when develop
baseurl:            "" # the subpath of your site, e.g. /blog


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           Asia/Seoul
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           5
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  imput:            GFM

# Navigation
nav:
  - name:           "About"
    url:            "/about"
  - name:           "Archive"
    url:            "/archive"
  - name:           "Tags"
    url:            "/tags"
  - name:           "Github"
    url:            "https://github.com/anifilm/anifilm.github.io"



# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
gems:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-admin
  - jekyll-sitemap

exclude:            [vendor]
